# Generated by Django 4.0.2 on 2022-03-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField()),
                ('faculty_name', models.CharField(max_length=30)),
                ('faculty_place', models.CharField(max_length=30)),
                ('faculty_position', models.CharField(max_length=40)),
            ],
        ),
    ]
