# Generated by Django 4.0.2 on 2022-03-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
