# Generated by Django 4.0.2 on 2022-03-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_faculty_faculty_password_alter_faculty_faculty_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_password',
            field=models.CharField(max_length=40),
        ),
    ]
